<!DOCTYPE html>
<html lang="en">
  <!-- Head tag -->
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Title -->
  
  <title>前端项目中常见的异常处理 - Hexo</title>

  <!--Favicon-->
  <link rel="icon" href="favicon/favicon.ico">

  <!--Description-->
  
      <meta name="description" content="​     在平常的前端项目开发中，稍有不小心就会遇到报错等异常问题，有时候要经过很多次的反复调试才能找到bug所在，实在很棘手，这里总结了一些常见的异常问题，方便以后提高解决问题的效率。首先我们先探讨一些问题：
一、为什么要处理异常？异常是不可控的，会影响最终的呈现结果，但是我们有充分的理由去做这">
  

  <!--Author-->
  
      <meta name="author" content="John Doe">
  

  <!-- Pure CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Crimson+Text|Open+Sans:300,800" rel="stylesheet">

  <!-- Custom CSS -->
  
<link rel="stylesheet" href="/css/styles.css">


  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Analytics -->
  

<meta name="generator" content="Hexo 5.0.0"></head>


  <body>
  	<div class="container-fluid navbar-container m-sm-5">
      <!-- Header -->
      <nav class="navbar navbar-toggleable-sm navbar-light px-1 py-3 my-3 mb-sm-5">
  <a class="navbar-brand ml-2" href="/">Hexo</a>
  <button class="navbar-toggler navbar-toggler-right py-2" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse text-center" id="navbarCollapse">
    <ul class="navbar-nav ml-auto my-auto">
      
    </ul>
    <hr class="hidden-md-up" />
  </div>
</nav>


  		<div class="row">
  			<div class="col-12 mb-4">
  <img class="img-fluid project-img" src="/images/unsplash.jpg" alt="前端项目中常见的异常处理">
</div>
<div class="col-lg-4 col-12 pt-3 px-4 pr-lg-5">
  <h1>前端项目中常见的异常处理</h1>
</div>
<div class="col-lg-8 col-12 pt-lg-3 mb-4 pl-lg-5 px-lg-0 px-4 portfolio-content">
  <p>​     在平常的前端项目开发中，稍有不小心就会遇到报错等异常问题，有时候要经过很多次的反复调试才能找到bug所在，实在很棘手，这里总结了一些常见的异常问题，方便以后提高解决问题的效率。首先我们先探讨一些问题：</p>
<h3 id="一、为什么要处理异常？"><a href="#一、为什么要处理异常？" class="headerlink" title="一、为什么要处理异常？"></a>一、为什么要处理异常？</h3><p>异常是不可控的，会影响最终的呈现结果，但是我们有充分的理由去做这样的事情。</p>
<ol>
<li>增强用户体验；</li>
<li>远程定位问题；</li>
<li>未雨绸缪，及早发现问题；</li>
<li>无法复线问题，尤其是移动端，机型，系统都是问题；</li>
<li>完善的前端方案，前端监控系统；</li>
</ol>
<p>对于 JS 而言，我们面对的仅仅只是异常，异常的出现不会直接导致 JS 引擎崩溃，最多只会使当前执行的任务终止。</p>
<h3 id="二、需要处理哪些异常？"><a href="#二、需要处理哪些异常？" class="headerlink" title="二、需要处理哪些异常？"></a>二、需要处理哪些异常？</h3><p>对于前端来说，我们可做的异常捕获还真不少。总结一下，大概如下：</p>
<ul>
<li><p>JS 语法错误、代码异常</p>
</li>
<li><p>AJAX 请求异常</p>
</li>
<li><p>静态资源加载异常</p>
</li>
<li><p>Promise 异常</p>
</li>
<li><p>Iframe 异常</p>
</li>
<li><p>跨域 Script error</p>
</li>
<li><p>崩溃和卡顿</p>
<h3 id="三、Try-Catch-的误区"><a href="#三、Try-Catch-的误区" class="headerlink" title="三、Try-Catch 的误区"></a>三、Try-Catch 的误区</h3><p>try-catch 只能捕获到同步的运行时错误，对语法和异步错误却无能为力，捕获不到。</p>
<ol>
<li>同步运行时错误：</li>
</ol>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">try &#123;</span><br><span class="line">  let name &#x3D; &#39;jartto&#39;;</span><br><span class="line">  console.log(nam);</span><br><span class="line">&#125; catch(e) &#123;</span><br><span class="line">  console.log(&#39;捕获到异常：&#39;,e);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>输出：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">捕获到异常：ReferenceError: nam is not defined</span><br><span class="line">    at &lt;anonymous&gt;:3:15</span><br></pre></td></tr></table></figure>

<p>2.不能捕获到具体的语法错误，只有一个语法错误提示。我们修改一下代码，删掉一个单引号：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">try &#123;</span><br><span class="line">  let name &#x3D; &#39;jartto;</span><br><span class="line">  console.log(nam);</span><br><span class="line">&#125; catch(e) &#123;</span><br><span class="line"></span><br><span class="line">  console.log(&#39;捕获到异常：&#39;,e);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

</li>
</ul>
<p>输出：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Uncaught SyntaxError: Invalid or unexpected token</span><br><span class="line">不过语法错误在我们开发阶段就可以看到，应该不会顺利上到线上环境。</span><br></pre></td></tr></table></figure>

<p>3.异步错误</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">try &#123;</span><br><span class="line">  setTimeout(() &#x3D;&gt; &#123;</span><br><span class="line">    undefined.map(v &#x3D;&gt; v);</span><br><span class="line">  &#125;, 1000)</span><br><span class="line">&#125; catch(e) &#123;</span><br><span class="line">  console.log(&#39;捕获到异常：&#39;,e);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>日志显示：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Uncaught TypeError: Cannot read property &#39;map&#39; of undefined</span><br><span class="line">    at setTimeout (&lt;anonymous&gt;:3:11)</span><br></pre></td></tr></table></figure>

<p>然而并没有捕获到异常。</p>
<h3 id="四、window-onerror"><a href="#四、window-onerror" class="headerlink" title="四、window.onerror"></a>四、window.onerror</h3><p>当 JS 运行时错误发生时，window 会触发一个 ErrorEvent 接口的 error 事件，并执行 window.onerror()。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">&#x2F;**</span><br><span class="line">* @param &#123;String&#125;  message    错误信息</span><br><span class="line">* @param &#123;String&#125;  source    出错文件</span><br><span class="line">* @param &#123;Number&#125;  lineno    行号</span><br><span class="line">* @param &#123;Number&#125;  colno    列号</span><br><span class="line">* @param &#123;Object&#125;  error  Error对象（对象）</span><br><span class="line">*&#x2F;</span><br><span class="line"></span><br><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">   console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<ol>
<li>首先试试同步运行时错误</li>
</ol>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">&#x2F;&#x2F; message：错误信息（字符串）。</span><br><span class="line">&#x2F;&#x2F; source：发生错误的脚本URL（字符串）</span><br><span class="line">&#x2F;&#x2F; lineno：发生错误的行号（数字）</span><br><span class="line">&#x2F;&#x2F; colno：发生错误的列号（数字）</span><br><span class="line">&#x2F;&#x2F; error：Error对象（对象）</span><br><span class="line">console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">&#125;</span><br><span class="line">Jartto;</span><br></pre></td></tr></table></figure>

<p>查看结果发现我们捕获到了异常：</p>
<p>2.再试试语法错误</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">&#125;</span><br><span class="line">let name &#x3D; &#39;Jartto</span><br></pre></td></tr></table></figure>

<p>控制台打印出了这样的异常：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">Uncaught SyntaxError: Invalid or unexpected token</span><br></pre></td></tr></table></figure>

<p>3.最后试试异步运行时错误：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">    console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">&#125;</span><br><span class="line">setTimeout(() &#x3D;&gt; &#123;</span><br><span class="line">    Jartto;</span><br><span class="line">&#125;);</span><br></pre></td></tr></table></figure>

<p>控制台输出了：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">捕获到异常：&#123;message: &quot;Uncaught ReferenceError: Jartto is not defined&quot;, source: &quot;http:&#x2F;&#x2F;127.0.0.1:8001&#x2F;&quot;, lineno: 36, colno: 5, error: ReferenceError: Jartto is not defined</span><br><span class="line">    at setTimeout (http:&#x2F;&#x2F;127.0.0.1:8001&#x2F;:36:5)&#125;</span><br></pre></td></tr></table></figure>

<p>4.再试试网络请求异常的情况：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">&lt;script&gt;</span><br><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">    console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">    return true;</span><br><span class="line">&#125;</span><br><span class="line">&lt;&#x2F;script&gt;</span><br><span class="line">&lt;img src&#x3D;&quot;.&#x2F;jartto.png&quot;&gt;</span><br></pre></td></tr></table></figure>

<p><strong><code>我们发现，不论是静态资源异常，或者接口异常，错误都无法捕获到。</code></strong></p>
<p>补充一点：window.onerror 函数只有在返回 true 的时候，异常才不会向上抛出，否则即使是知道异常的发生控制台还是会显示 Uncaught Error: xxxxx</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">    console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">    return true;</span><br><span class="line">&#125;</span><br><span class="line">setTimeout(() &#x3D;&gt; &#123;</span><br><span class="line">    Jartto;</span><br><span class="line">&#125;);</span><br></pre></td></tr></table></figure>

<p>控制台就不会再有这样的错误了：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Uncaught ReferenceError: Jartto is not defined</span><br><span class="line">    at setTimeout ((index):36)</span><br></pre></td></tr></table></figure>

<p>需要注意：</p>
<ul>
<li>onerror 最好写在所有 JS 脚本的前面，否则有可能捕获不到错误；</li>
<li>onerror 无法捕获语法错误；</li>
</ul>
<p>在实际的使用过程中，onerror 主要是来捕获预料之外的错误，而 try-catch 则是用来在可预见情况下监控特定的错误，两者结合使用更加高效。</p>
<h3 id="五、window-addEventListener"><a href="#五、window-addEventListener" class="headerlink" title="五、window.addEventListener"></a>五、window.addEventListener</h3><p>当一项资源（如图片或脚本）加载失败，加载资源的元素会触发一个 Event 接口的 error 事件，并执行该元素上的onerror() 处理函数。这些 error 事件不会向上冒泡到 window ，不过（至少在 Firefox 中）能被单一的window.addEventListener 捕获。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">&lt;scritp&gt;</span><br><span class="line">window.addEventListener(&#39;error&#39;, (error) &#x3D;&gt; &#123;</span><br><span class="line">    console.log(&#39;捕获到异常：&#39;, error);</span><br><span class="line">&#125;, true)</span><br><span class="line">&lt;&#x2F;script&gt;</span><br><span class="line">&lt;img src&#x3D;&quot;.&#x2F;jartto.png&quot;&gt;</span><br></pre></td></tr></table></figure>

<p>此时控制台会输出“捕获到异常”的结果。</p>
<p>由于网络请求异常不会事件冒泡，因此必须在捕获阶段将其捕捉到才行，但是这种方式虽然可以捕捉到网络请求的异常，但是无法判断 HTTP 的状态是 404 还是其他比如 500 等等，所以还需要配合服务端日志才进行排查分析才可以。</p>
<p><strong>需要注意的是：</strong></p>
<ul>
<li>不同浏览器下返回的 error 对象可能不同，需要注意兼容处理。</li>
<li>需要注意避免 addEventListener 重复监听。</li>
</ul>
<h3 id="六、Promise-Catch"><a href="#六、Promise-Catch" class="headerlink" title="六、Promise Catch"></a>六、Promise Catch</h3><p>在 promise 中使用 catch 可以非常方便的捕获到异步 error ，这个很简单。</p>
<p>没有写 catch 的 Promise 中抛出的错误无法被 onerror 或 try-catch 捕获到，所以我们务必要在 Promise 中不要忘记写 catch 处理抛出的异常。</p>
<p>解决方案：为了防止有漏掉的 Promise 异常，建议在全局增加一个对 unhandledrejection 的监听，用来全局监听Uncaught Promise Error。使用方式：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">window.addEventListener(&quot;unhandledrejection&quot;, function(e)&#123;</span><br><span class="line">  console.log(e);</span><br><span class="line">&#125;);</span><br></pre></td></tr></table></figure>

<p>尝试一下下面的方法，并查看输出结果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">window.addEventListener(&quot;unhandledrejection&quot;, function(e)&#123;</span><br><span class="line">  e.preventDefault()</span><br><span class="line">  console.log(&#39;捕获到异常：&#39;, e);</span><br><span class="line">  return true;</span><br><span class="line">&#125;);</span><br><span class="line">Promise.reject(&#39;promise error&#39;);</span><br></pre></td></tr></table></figure>

<p>那如果对 Promise 不进行 catch 呢？</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">window.addEventListener(&quot;unhandledrejection&quot;, function(e)&#123;</span><br><span class="line">  e.preventDefault()</span><br><span class="line">  console.log(&#39;捕获到异常：&#39;, e);</span><br><span class="line">  return true;</span><br><span class="line">&#125;);</span><br><span class="line">new Promise((resolve, reject) &#x3D;&gt; &#123;</span><br><span class="line">  reject(&#39;jartto: promise error&#39;);</span><br><span class="line">&#125;);</span><br></pre></td></tr></table></figure>

<p>事实证明，也是会被正常捕获到的。</p>
<p>所以，为了防止有漏掉的 Promise 异常，建议在全局增加一个对 unhandledrejection 的监听，用来全局监听 Uncaught Promise Error。</p>
<p>补充一点：如果去掉控制台的异常显示，需要加上：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">event.preventDefault();</span><br></pre></td></tr></table></figure>

<h3 id="七、VUE-errorHandler"><a href="#七、VUE-errorHandler" class="headerlink" title="七、VUE errorHandler"></a>七、VUE errorHandler</h3><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">Vue.config.errorHandler &#x3D; (err, vm, info) &#x3D;&gt; &#123;</span><br><span class="line">  console.error(&#39;通过vue errorHandler捕获的错误&#39;);</span><br><span class="line">  console.error(err);</span><br><span class="line">  console.error(vm);</span><br><span class="line">  console.error(info);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h3 id="八、iframe-异常"><a href="#八、iframe-异常" class="headerlink" title="八、iframe 异常"></a>八、iframe 异常</h3><p>对于 iframe 的异常捕获，我们还得借力 window.onerror：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">window.onerror &#x3D; function(message, source, lineno, colno, error) &#123;</span><br><span class="line">  console.log(&#39;捕获到异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>一个简单的例子可能如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line">&lt;iframe src&#x3D;&quot;.&#x2F;iframe.html&quot; frameborder&#x3D;&quot;0&quot;&gt;&lt;&#x2F;iframe&gt;</span><br><span class="line">&lt;script&gt;</span><br><span class="line">  window.frames[0].onerror &#x3D; function (message, source, lineno, colno, error) &#123;</span><br><span class="line">    console.log(&#39;捕获到 iframe 异常：&#39;,&#123;message, source, lineno, colno, error&#125;);</span><br><span class="line">    return true;</span><br><span class="line">  &#125;;</span><br><span class="line">&lt;&#x2F;script&gt;</span><br></pre></td></tr></table></figure>

<h3 id="九、Script-error"><a href="#九、Script-error" class="headerlink" title="九、Script error"></a>九、Script error</h3><p>一般情况，如果出现 Script error 这样的错误，基本上可以确定是出现了跨域问题。这时候，是不会有其他太多辅助信息的，但是解决思路无非如下：</p>
<p>跨源资源共享机制( CORS )：我们为 script 标签添加 crossOrigin 属性。</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">&lt;script src&#x3D;&quot;http:&#x2F;&#x2F;jartto.wang&#x2F;main.js&quot; crossorigin&gt;&lt;&#x2F;script&gt;</span><br></pre></td></tr></table></figure>

<p>或者动态去添加 js 脚本：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">const script &#x3D; document.createElement(&#39;script&#39;);</span><br><span class="line">script.crossOrigin &#x3D; &#39;anonymous&#39;;</span><br><span class="line">script.src &#x3D; url;</span><br><span class="line">document.body.appendChild(script);</span><br></pre></td></tr></table></figure>

<p>特别注意，服务器端需要设置：Access-Control-Allow-Origin</p>
<p>此外，我们也可以试试这个-解决 Script Error 的另类思路：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">const originAddEventListener &#x3D; EventTarget.prototype.addEventListener;</span><br><span class="line">EventTarget.prototype.addEventListener &#x3D; function (type, listener, options) &#123;</span><br><span class="line">  const wrappedListener &#x3D; function (...args) &#123;</span><br><span class="line">    try &#123;</span><br><span class="line">      return listener.apply(this, args);</span><br><span class="line">    &#125;</span><br><span class="line">    catch (err) &#123;</span><br><span class="line">      throw err;</span><br><span class="line">    &#125;</span><br><span class="line">  &#125;</span><br><span class="line">  return originAddEventListener.call(this, type, wrappedListener, options);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>简单解释一下：</p>
<p>改写了 EventTarget 的 addEventListener 方法；对传入的 listener 进行包装，返回包装过的 listener，对其执行进行 try-catch；浏览器不会对 try-catch 起来的异常进行跨域拦截，所以 catch 到的时候，是有堆栈信息的；重新 throw 出来异常的时候，执行的是同域代码，所以 window.onerror 捕获的时候不会丢失堆栈信息；利用包装 addEventListener，我们还可以达到「扩展堆栈」的效果：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">(() &#x3D;&gt; &#123;</span><br><span class="line">   const originAddEventListener &#x3D; EventTarget.prototype.addEventListener;</span><br><span class="line">   EventTarget.prototype.addEventListener &#x3D; function (type, listener, options) &#123;</span><br><span class="line">+    &#x2F;&#x2F; 捕获添加事件时的堆栈</span><br><span class="line">+    const addStack &#x3D; new Error(&#96;Event ($&#123;type&#125;)&#96;).stack;</span><br><span class="line">     const wrappedListener &#x3D; function (...args) &#123;</span><br><span class="line">       try &#123;</span><br><span class="line">         return listener.apply(this, args);</span><br><span class="line">       &#125;</span><br><span class="line">       catch (err) &#123;</span><br><span class="line">+        &#x2F;&#x2F; 异常发生时，扩展堆栈</span><br><span class="line">+        err.stack +&#x3D; &#39;\n&#39; + addStack;</span><br><span class="line">         throw err;</span><br><span class="line">       &#125;</span><br><span class="line">     &#125;</span><br><span class="line">     return originAddEventListener.call(this, type, wrappedListener, options);</span><br><span class="line">   &#125;</span><br><span class="line"> &#125;)();</span><br></pre></td></tr></table></figure>

<h3 id="十、崩溃和卡顿"><a href="#十、崩溃和卡顿" class="headerlink" title="十、崩溃和卡顿"></a>十、崩溃和卡顿</h3><p>卡顿也就是网页暂时响应比较慢， JS 可能无法及时执行。但崩溃就不一样了，网页都崩溃了，JS 都不运行了，还有什么办法可以监控网页的崩溃，并将网页崩溃上报呢？</p>
<p>崩溃和卡顿也是不可忽视的，也许会导致用户流失。</p>
<ol>
<li>利用 window 对象的 load 和 beforeunload 事件实现了网页崩溃的监控。不错的文章，推荐阅读：Logging Information on Browser Crashes。</li>
</ol>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">window.addEventListener(&#39;load&#39;, function () &#123;</span><br><span class="line">    sessionStorage.setItem(&#39;good_exit&#39;, &#39;pending&#39;);</span><br><span class="line">    setInterval(function () &#123;</span><br><span class="line">        sessionStorage.setItem(&#39;time_before_crash&#39;, new Date().toString());</span><br><span class="line">    &#125;, 1000);</span><br><span class="line">  &#125;);</span><br><span class="line"></span><br><span class="line">  window.addEventListener(&#39;beforeunload&#39;, function () &#123;</span><br><span class="line">    sessionStorage.setItem(&#39;good_exit&#39;, &#39;true&#39;);</span><br><span class="line">  &#125;);</span><br><span class="line"></span><br><span class="line">  if(sessionStorage.getItem(&#39;good_exit&#39;) &amp;&amp;</span><br><span class="line">    sessionStorage.getItem(&#39;good_exit&#39;) !&#x3D;&#x3D; &#39;true&#39;) &#123;</span><br><span class="line">    &#x2F;*</span><br><span class="line">        insert crash logging code here</span><br><span class="line">    *&#x2F;</span><br><span class="line">    alert(&#39;Hey, welcome back from your crash, looks like you crashed on: &#39; + sessionStorage.getItem(&#39;time_before_crash&#39;));</span><br><span class="line">  &#125;</span><br></pre></td></tr></table></figure>

<p>2.基于以下原因，我们可以使用 Service Worker 来实现网页崩溃的监控：</p>
<p>Service Worker 有自己独立的工作线程，与网页区分开，网页崩溃了，Service Worker 一般情况下不会崩溃；Service Worker 生命周期一般要比网页还要长，可以用来监控网页的状态；网页可以通过 navigator.serviceWorker.controller.postMessage API 向掌管自己的 SW 发送消息。</p>
<h3 id="十一、错误上报"><a href="#十一、错误上报" class="headerlink" title="十一、错误上报"></a>十一、错误上报</h3><p>1.通过 Ajax 发送数据 因为 Ajax 请求本身也有可能会发生异常，而且有可能会引发跨域问题，一般情况下更推荐使用动态创建 img 标签的形式进行上报。</p>
<p>2.动态创建 img 标签的形式</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">function report(error) &#123;</span><br><span class="line">  let reportUrl &#x3D; &#39;http:&#x2F;&#x2F;jartto.wang&#x2F;report&#39;;</span><br><span class="line">  new Image().src &#x3D; &#96;$&#123;reportUrl&#125;?logs&#x3D;$&#123;error&#125;&#96;;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>实际操作中，如果你的网站访问量很大，那么一个必然的错误发送的信息就有很多条，这时候，我们需要设置采集率，从而减缓服务器的压力：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">Reporter.send &#x3D; function(data) &#123;</span><br><span class="line">  &#x2F;&#x2F; 只采集 30%</span><br><span class="line">  if(Math.random() &lt; 0.3) &#123;</span><br><span class="line">    send(data)      &#x2F;&#x2F; 上报错误信息</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>采集率应该通过实际情况来设定，随机数，或者某些用户特征都是不错的选择。</p>
<h3 id="十二、总结"><a href="#十二、总结" class="headerlink" title="十二、总结"></a>十二、总结</h3><p>所以，如何处理异常呢？可以通过以下这些解决办法，采用组合方案，分类型的去捕获异常：</p>
<ol>
<li>可疑区域增加 Try-Catch</li>
<li>全局监控 JS 异常 window.onerror</li>
<li>全局监控静态资源异常 window.addEventListener</li>
<li>捕获没有 Catch 的 Promise 异常：unhandledrejection</li>
<li>VUE errorHandler 和 React componentDidCatch</li>
<li>监控网页崩溃：window 对象的 load 和 beforeunload</li>
<li>跨域 crossOrigin 解决</li>
</ol>

</div>


      </div>
      
  	</div>

    <!-- After footer scripts -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

  </body>
</html>
